const LABELS: Record<string, string> = {
  ACTIVE: '正常',
  INACTIVE: '已停用',
  DIRECT_FROM_LOCATION: '指定仓库直发',
  EXTERNAL_WAREHOUSE: '外部平台仓',
  VIRTUAL_ALLOCATION: '虚拟渠道额度',
  AVAILABLE: '可售',
  QC_PENDING: '待质检',
  DEFECTIVE: '不良品',
  SUPPLIER_CLAIM: '供应商索赔',
  SCRAPPED: '已报废',
  PHYSICAL_WAREHOUSE: '物理仓库',
  QC_AREA: '待质检区',
  DEFECTIVE_AREA: '不良品区',
  CLAIM_AREA: '供应商索赔区',
  SCRAP_AREA: '报废区',
  OPENING_IN: '期初入库',
  ADJUSTMENT_IN: '库存调增',
  ADJUSTMENT_OUT: '库存调减',
  TRANSFER_OUT: '调拨出库',
  TRANSFER_IN: '调拨入库',
  PURCHASE_RECEIPT: '采购收货',
  PURCHASE_RETURN: '采购退货',
  SALES_ISSUE: '销售出库',
  SALES_RETURN_QC: '销售退货待检',
  QC_RELEASE: '质检转可售',
  QC_DEFECTIVE: '质检转不良',
  QC_CLAIM: '质检转索赔',
  SCRAP: '报废',
  SUPPLIER_REPLACEMENT: '供应商换货',
  REVERSAL: '冲销',
  DRAFT: '草稿',
  POSTED: '已过账',
  CANCELLED: '已取消',
  CONFIRMED: '已确认',
  PARTIALLY_RECEIVED: '部分收货',
  RECEIVED: '已收货',
  OPEN: '待处理',
  PARTIALLY_PAID: '部分付款',
  SETTLED: '已结清',
  VOID: '已作废',
  PARTIALLY_APPLIED: '部分抵扣',
  APPLIED: '已抵扣',
  PARTIALLY_ISSUED: '部分出库',
  ISSUED: '已出库',
  PAID: '已完成',
  UNKNOWN: '待确认',
  SUPPLIER: '供应商',
  CUSTOMER: '客户',
  LOGISTICS: '物流',
  INTERNAL: '内部',
  CLAIMED: '已索赔',
  RESOLVED: '已解决',
  CLOSED: '已关闭',
  SUBMITTED: '已提交',
  PARTIALLY_SETTLED: '部分结算',
  REJECTED: '已拒绝',
  REPLACEMENT: '供应商换货',
  CASH_COMPENSATION: '现金赔付',
  CREDIT_COMPENSATION: '下次抵扣',
  SELF_BEAR: '自行承担',
  BANK: '银行卡',
  ALIPAY: '支付宝',
  PAYPAL: 'PayPal',
  PLATFORM_BALANCE: '平台余额',
  CASH: '现金',
  OTHER: '其他',
  CNY: '人民币（CNY）',
  IN: '流入',
  OUT: '流出',
  SALES_RECEIPT: '销售回款',
  PURCHASE_PAYMENT: '采购付款',
  CUSTOMER_REFUND: '客户退款',
  PLATFORM_FEE: '平台费',
  LOGISTICS_FEE: '物流费',
  OTHER_INCOME: '其他收入',
  OTHER_EXPENSE: '其他费用',
  ACCOUNT_ADJUSTMENT: '账户调整',
  SUPPLIER_COMPENSATION: '供应商赔付',
  OFFICE_SUPPLIES: '办公耗材',
  QUALIFICATION: '资质办理',
  PREMISES: '店铺费用',
  UTILITIES: '通讯水电',
  TRAVEL: '差旅交通',
  EXPENSE_BILL: '日常开销账单',
  ONEDRIVE: 'OneDrive',
  MOCK_LOCAL: '本地模拟存储',
  PENDING: '待处理',
  UPLOADING: '正在上传',
  SYNCED: '已同步',
  FAILED: '失败',
  SUCCESS: '成功',
  DELETED: '已删除',
  CREATING: '正在生成',
  VERIFIED: '校验通过',
  EXPIRED: '已按策略清理',
  POSTGRES_CUSTOM: 'PostgreSQL 自定义备份',
  MANUAL: '手工备份',
  STARTUP_COMPENSATION: '启动补偿',
  OPERATION_THRESHOLD: '业务量触发',
  PRE_RESTORE: '恢复前保护',
  BOOTSTRAP_IMPORT: 'Bootstrap 导入',
  AUTH: '认证',
  BACKUP: '备份恢复',
  FINANCE: '财务',
  INVENTORY: '库存',
  MASTER_DATA: '基础资料',
  PURCHASE: '采购',
  QUALITY: '质量',
  SALES: '销售',
  AdminUser: '管理员',
  BackupHistory: '备份记录',
  FileAsset: '备份文件',
  OneDriveConnection: 'OneDrive 连接',
  FinancialAccount: '资金账户',
  AccountAdjustment: '账户调整',
  ExpenseBill: '日常开销账单',
  Payment: '付款单',
  Receipt: '收款单',
  ChannelAllocation: '渠道额度分配',
  InventoryLocation: '库存地点',
  InventoryOpening: '期初库存',
  InventoryAdjustment: '库存调整',
  InventoryTransfer: '库存调拨',
  PurchaseReceipt: '采购收货',
  PurchaseReturn: '采购退货',
  SalesIssue: '销售出库',
  SalesReturn: '销售退货',
  QualityInspection: '质检单',
  SupplierClaim: '供应商索赔',
  SupplierClaimSettlement: '索赔处理',
  categories: '商品类目',
  products: '商品',
  skus: 'SKU',
  units: '基础单位',
  suppliers: '供应商',
  buyers: '采购员',
  purchaseChannels: '采购渠道',
  salesChannels: '销售渠道',
  customers: '客户',
};

const ACTION_WORDS: Record<string, string> = {
  ACCOUNT: '账户',
  ADJUSTMENT: '调整',
  ADMIN: '管理员',
  ALLOCATE: '分配',
  BOOTSTRAP: '初始化',
  CANCEL: '取消',
  CHANGE: '修改',
  CHANNEL: '渠道',
  CLAIM: '索赔',
  COMPENSATION: '补偿',
  CONFIRM: '确认',
  CREATE: '创建',
  DEACTIVATE: '停用',
  DEVICE: '设备',
  DISCONNECT: '断开连接',
  EXPIRE: '清理',
  EXPENSE: '开销',
  FILE: '文件',
  BILL: '账单',
  IMPORT: '导入',
  INSPECTION: '质检',
  INTERNAL: '内部',
  ISSUE: '出库',
  LOCATION: '地点',
  LOGIN: '登录',
  LOGOUT: '退出登录',
  OPENING: '期初',
  ORDER: '订单',
  PAYMENT: '付款',
  PASSWORD: '密码',
  POST: '过账',
  PRICE: '报价',
  RECEIPT: '收款',
  RESTORE: '恢复',
  RETENTION: '保留策略',
  RETURN: '退货',
  SETTLE: '结算',
  START: '启动',
  STARTUP: '启动',
  STORE: '保存',
  TRANSFER: '调拨',
  UPDATE: '更新',
  VERIFY: '校验',
};

export function enumLabel(value: unknown): string {
  const raw = String(value ?? '');
  return LABELS[raw] ?? raw;
}

export function auditActionLabel(value: unknown): string {
  return String(value ?? '')
    .split('_')
    .map((part) => ACTION_WORDS[part] ?? part)
    .join('');
}
